version: '2'
services:
    go:
        build: .
        image: chyeh-recipe-api
        ports:
            - "80:80"
        links:
            - postgres
        environment:
            PORT: '80'
            DSN: 'postgres://hellofresh:hellofresh@postgres:5432/hellofresh?sslmode=disable'
        command: ["scripts/wait-for-postgres.sh", "postgres", "hellofresh", "hellofresh", "hellofresh", "app"]
    postgres:
        image: onjin/alpine-postgres:9.5
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: hellofresh
            POSTGRES_PASSWORD: hellofresh
            POSTGRES_DB: hellofresh
